<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class TestimonialsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('testimonials')->insert([
            ['id' => Str::uuid(), 'alumni' => 'Rodrigo Marciano', 'testimonial' => 'Nasci em Jacareí, onde cresci e estudei até o ensino médio, quando eu ganhei um concurso para fazer intercâmbio nos EUA. Nesta época, início dos anos 2000, eu fui aluno do Nicolas, e sou muito grato pelas aulas e conselhos que foram fundamentais para que eu ganhasse este concurso, além do incentivo para sonhar com vôos maiores. Retornei ao Brasil em 2004, fiz faculdade de administração de empresas e ingressei no mercado financeiro. Hoje sou Vice-Presidente de risco de crédito do maior banco dos Estados Unidos e trabalho em NY há 2 anos. Dream on!', 'university' => 'FGV - Fundação Getulio Vargas', 'photo' => 'https://img.freepik.com/fotos-gratis/retrato-de-uma-jovem-bonita-em-pe-na-parede-cinza_231208-10760.jpg?w=740&t=st=1683325625~exp=1683326225~hmac=6bbe19ab443b16996211ed2e31885753d16c8828e823919b27259e1065efc5cc'],
            ['id' => Str::uuid(), 'alumni' => 'Alisson Brito', 'testimonial' => 'É um prazer escrever esta breve declaração atestando o Instituto Van Veen e, ao mesmo tempo, convidá-lo a apoiar e fazer parte desta iniciativa. Como aluno e também ex-voluntário, estou feliz e orgulhoso de saber que temos uma iniciativa tão extraordinária no Brasil que tem impactado positivamente os estudantes e a vida de suas famílias. Além disso, gostaria de expressar minha gratidão ao Sr. Nicolas Van Veen que, na minha opinião, é um empreendedor brilhante e trabalhador.', 'university' => 'Coventry University - Inglaterra', 'photo' => 'https://img.freepik.com/fotos-gratis/homem-de-negocios-feliz-em-pe-sorrindo-isolado-no-fundo-cinza-do-estudio-belo-retrato-masculino-com-metade-do-corpo-jovem-satisfazer-o-homem-emocoes-humanas-conceito-de-expressao-facial_155003-31361.jpg?w=740&t=st=1683325641~exp=1683326241~hmac=f4aa71e6d071e71201480b76887130890394fb18f0995caf1dda18634a9899ee'],
            ['id' => Str::uuid(), 'alumni' => 'Marcella Cardoso', 'testimonial' => '“Agradecer é lembrar que nada nesta vida se consegue sozinho… Agradeço ao Instituto Van Veen por me mostrar que os sonhos se expandem ou se encolhem na proporção da nossa coragem, da nossa disciplina e dedicação. E hoje agradeço a todo profissionalismo, a expertise incrível de cada professora e o incentivo constante. Muito obrigada por estarem comigo nessa luta, por toda atenção ao prepararem as aulas para mim e por me ajudarem a superar meus limites! Fui aprovada para fazer meu doutorado na Harvard Medical School com bolsa de estudos e sigo imprimindo meu sonho na minha história! Todos nós temos histórias únicas que merecem ser contadas. Qual será a sua?”', 'university' => 'Harvard Medical School - EUA', 'photo' => 'https://img.freepik.com/fotos-gratis/jovem-afro-americano-bonito-com-camiseta-caqui_176420-32042.jpg?w=740&t=st=1683325663~exp=1683326263~hmac=f8d836e3bc4afbadf65b491d60573dec57e6f42e3976dba743204ac16c0e1aab'],
            ['id' => Str::uuid(), 'alumni' => 'Vinicius Bastos', 'testimonial' => 'Nunca imaginei que esse dia chegaria, mas aqui estou eu. Após duros anos de aprendizado e de formação pessoal e acadêmica no Instituto Van Veen, posso dizer com firmeza que estou pronto para o que o mundo tem a me oferecer. Durante meu tempo no Instituto, pude perceber meu crescimento como aluno, mas principalmente como humano. De Joseph Campbell à Benjamin Franklin, a cada aula eu via o mundo se abrir diante de mim, e a cada segundo, eu me via mais perto do meu sonho. Hoje, aprovado em uma universidade de ponta na Coréia do Sul e com uma bolsa de estudos incrível, não consigo achar palavras para descrever minha gratidão ao Nicolas Van Veen e a todos aqueles que fizeram parte de minha jornada. Sigam seus sonhos e sejam livres, e nunca tenham medo de falhar, pois é só com a derrota que nasce um herói.', 'university' => 'Sungkyunkwan University - Coréia do Sul', 'photo' => 'https://img.freepik.com/fotos-gratis/retrato-de-corpo-inteiro-de-homem-barbudo-na-camisa-apontando-para-fora_171337-15725.jpg?w=360&t=st=1683325671~exp=1683326271~hmac=062fd5e1b86b6ff520b5044c2cdd1af2e7dca4822470d9d5e3697725dc455f99'],
            ['id' => Str::uuid(), 'alumni' => 'Ana Claudia da Rocha', 'testimonial' => 'Meu nome é Ana Claudia da Rocha. Eu fui aprovada recentemente para receber uma bolsa de mestrado na Rússia da agência Rossotrudnichestvo! Um dos objetivos traçados desde o início da minha graduação é o de estudar fora do país. Eu acredito que estar em contato com novas formas de ensino e diferentes modos de pensar geram desenvolvimento tanto pessoal quanto dentro da minha área de estudo (Geologia). Conheci o instituto Van Veen no início desse ano (2019), e me foram apresentadas inúmeras possibilidades e meios para a realização desse meu sonho. Sou muito grata ao Nicolas Van Veen, e aos professores e alunos dessa instituição pelo grande suporte, dedicação e disponibilidade!', 'university' => 'Saint Petersburg University - Rússia', 'photo' => 'https://img.freepik.com/psd-gratuitas/retrato-de-mulher-de-negocios_23-2150116810.jpg?w=360&t=st=1683325680~exp=1683326280~hmac=ca0f48801a5dcac701c9325ddc126ec9a289976dc6b436a5d9cca3ea4353ebca'],
        ]);
    }
}
